// Generated by gencpp from file rqt_mypkg/ArmService.msg
// DO NOT EDIT!


#ifndef RQT_MYPKG_MESSAGE_ARMSERVICE_H
#define RQT_MYPKG_MESSAGE_ARMSERVICE_H

#include <ros/service_traits.h>


#include <rqt_mypkg/ArmServiceRequest.h>
#include <rqt_mypkg/ArmServiceResponse.h>


namespace rqt_mypkg
{

struct ArmService
{

typedef ArmServiceRequest Request;
typedef ArmServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ArmService
} // namespace rqt_mypkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rqt_mypkg::ArmService > {
  static const char* value()
  {
    return "eab1f22ad728081e7b689c37e7f5d0fe";
  }

  static const char* value(const ::rqt_mypkg::ArmService&) { return value(); }
};

template<>
struct DataType< ::rqt_mypkg::ArmService > {
  static const char* value()
  {
    return "rqt_mypkg/ArmService";
  }

  static const char* value(const ::rqt_mypkg::ArmService&) { return value(); }
};


// service_traits::MD5Sum< ::rqt_mypkg::ArmServiceRequest> should match
// service_traits::MD5Sum< ::rqt_mypkg::ArmService >
template<>
struct MD5Sum< ::rqt_mypkg::ArmServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rqt_mypkg::ArmService >::value();
  }
  static const char* value(const ::rqt_mypkg::ArmServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rqt_mypkg::ArmServiceRequest> should match
// service_traits::DataType< ::rqt_mypkg::ArmService >
template<>
struct DataType< ::rqt_mypkg::ArmServiceRequest>
{
  static const char* value()
  {
    return DataType< ::rqt_mypkg::ArmService >::value();
  }
  static const char* value(const ::rqt_mypkg::ArmServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rqt_mypkg::ArmServiceResponse> should match
// service_traits::MD5Sum< ::rqt_mypkg::ArmService >
template<>
struct MD5Sum< ::rqt_mypkg::ArmServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rqt_mypkg::ArmService >::value();
  }
  static const char* value(const ::rqt_mypkg::ArmServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rqt_mypkg::ArmServiceResponse> should match
// service_traits::DataType< ::rqt_mypkg::ArmService >
template<>
struct DataType< ::rqt_mypkg::ArmServiceResponse>
{
  static const char* value()
  {
    return DataType< ::rqt_mypkg::ArmService >::value();
  }
  static const char* value(const ::rqt_mypkg::ArmServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RQT_MYPKG_MESSAGE_ARMSERVICE_H
