// Generated by gencpp from file rqt_mypkg/ArmServiceRequest.msg
// DO NOT EDIT!


#ifndef RQT_MYPKG_MESSAGE_ARMSERVICEREQUEST_H
#define RQT_MYPKG_MESSAGE_ARMSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rqt_mypkg
{
template <class ContainerAllocator>
struct ArmServiceRequest_
{
  typedef ArmServiceRequest_<ContainerAllocator> Type;

  ArmServiceRequest_()
    : Arm_isChecked(false)  {
    }
  ArmServiceRequest_(const ContainerAllocator& _alloc)
    : Arm_isChecked(false)  {
  (void)_alloc;
    }



   typedef uint8_t _Arm_isChecked_type;
  _Arm_isChecked_type Arm_isChecked;





  typedef boost::shared_ptr< ::rqt_mypkg::ArmServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rqt_mypkg::ArmServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ArmServiceRequest_

typedef ::rqt_mypkg::ArmServiceRequest_<std::allocator<void> > ArmServiceRequest;

typedef boost::shared_ptr< ::rqt_mypkg::ArmServiceRequest > ArmServiceRequestPtr;
typedef boost::shared_ptr< ::rqt_mypkg::ArmServiceRequest const> ArmServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rqt_mypkg::ArmServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rqt_mypkg::ArmServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rqt_mypkg::ArmServiceRequest_<ContainerAllocator1> & lhs, const ::rqt_mypkg::ArmServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.Arm_isChecked == rhs.Arm_isChecked;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rqt_mypkg::ArmServiceRequest_<ContainerAllocator1> & lhs, const ::rqt_mypkg::ArmServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rqt_mypkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rqt_mypkg::ArmServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rqt_mypkg::ArmServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rqt_mypkg::ArmServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rqt_mypkg::ArmServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rqt_mypkg::ArmServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rqt_mypkg::ArmServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rqt_mypkg::ArmServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eab1f22ad728081e7b689c37e7f5d0fe";
  }

  static const char* value(const ::rqt_mypkg::ArmServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeab1f22ad728081eULL;
  static const uint64_t static_value2 = 0x7b689c37e7f5d0feULL;
};

template<class ContainerAllocator>
struct DataType< ::rqt_mypkg::ArmServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rqt_mypkg/ArmServiceRequest";
  }

  static const char* value(const ::rqt_mypkg::ArmServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rqt_mypkg::ArmServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool Arm_isChecked\n"
;
  }

  static const char* value(const ::rqt_mypkg::ArmServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rqt_mypkg::ArmServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Arm_isChecked);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rqt_mypkg::ArmServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rqt_mypkg::ArmServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "Arm_isChecked: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Arm_isChecked);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RQT_MYPKG_MESSAGE_ARMSERVICEREQUEST_H
