// Generated by gencpp from file rqt_mypkg/DockService.msg
// DO NOT EDIT!


#ifndef RQT_MYPKG_MESSAGE_DOCKSERVICE_H
#define RQT_MYPKG_MESSAGE_DOCKSERVICE_H

#include <ros/service_traits.h>


#include <rqt_mypkg/DockServiceRequest.h>
#include <rqt_mypkg/DockServiceResponse.h>


namespace rqt_mypkg
{

struct DockService
{

typedef DockServiceRequest Request;
typedef DockServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DockService
} // namespace rqt_mypkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rqt_mypkg::DockService > {
  static const char* value()
  {
    return "176118c4f805289b178b248bb86fc0ac";
  }

  static const char* value(const ::rqt_mypkg::DockService&) { return value(); }
};

template<>
struct DataType< ::rqt_mypkg::DockService > {
  static const char* value()
  {
    return "rqt_mypkg/DockService";
  }

  static const char* value(const ::rqt_mypkg::DockService&) { return value(); }
};


// service_traits::MD5Sum< ::rqt_mypkg::DockServiceRequest> should match
// service_traits::MD5Sum< ::rqt_mypkg::DockService >
template<>
struct MD5Sum< ::rqt_mypkg::DockServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rqt_mypkg::DockService >::value();
  }
  static const char* value(const ::rqt_mypkg::DockServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rqt_mypkg::DockServiceRequest> should match
// service_traits::DataType< ::rqt_mypkg::DockService >
template<>
struct DataType< ::rqt_mypkg::DockServiceRequest>
{
  static const char* value()
  {
    return DataType< ::rqt_mypkg::DockService >::value();
  }
  static const char* value(const ::rqt_mypkg::DockServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rqt_mypkg::DockServiceResponse> should match
// service_traits::MD5Sum< ::rqt_mypkg::DockService >
template<>
struct MD5Sum< ::rqt_mypkg::DockServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rqt_mypkg::DockService >::value();
  }
  static const char* value(const ::rqt_mypkg::DockServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rqt_mypkg::DockServiceResponse> should match
// service_traits::DataType< ::rqt_mypkg::DockService >
template<>
struct DataType< ::rqt_mypkg::DockServiceResponse>
{
  static const char* value()
  {
    return DataType< ::rqt_mypkg::DockService >::value();
  }
  static const char* value(const ::rqt_mypkg::DockServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RQT_MYPKG_MESSAGE_DOCKSERVICE_H
