// Generated by gencpp from file rqt_mypkg/HoverService.msg
// DO NOT EDIT!


#ifndef RQT_MYPKG_MESSAGE_HOVERSERVICE_H
#define RQT_MYPKG_MESSAGE_HOVERSERVICE_H

#include <ros/service_traits.h>


#include <rqt_mypkg/HoverServiceRequest.h>
#include <rqt_mypkg/HoverServiceResponse.h>


namespace rqt_mypkg
{

struct HoverService
{

typedef HoverServiceRequest Request;
typedef HoverServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HoverService
} // namespace rqt_mypkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rqt_mypkg::HoverService > {
  static const char* value()
  {
    return "8930d5ae44ec72110e415a4dfe50939b";
  }

  static const char* value(const ::rqt_mypkg::HoverService&) { return value(); }
};

template<>
struct DataType< ::rqt_mypkg::HoverService > {
  static const char* value()
  {
    return "rqt_mypkg/HoverService";
  }

  static const char* value(const ::rqt_mypkg::HoverService&) { return value(); }
};


// service_traits::MD5Sum< ::rqt_mypkg::HoverServiceRequest> should match
// service_traits::MD5Sum< ::rqt_mypkg::HoverService >
template<>
struct MD5Sum< ::rqt_mypkg::HoverServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rqt_mypkg::HoverService >::value();
  }
  static const char* value(const ::rqt_mypkg::HoverServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rqt_mypkg::HoverServiceRequest> should match
// service_traits::DataType< ::rqt_mypkg::HoverService >
template<>
struct DataType< ::rqt_mypkg::HoverServiceRequest>
{
  static const char* value()
  {
    return DataType< ::rqt_mypkg::HoverService >::value();
  }
  static const char* value(const ::rqt_mypkg::HoverServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rqt_mypkg::HoverServiceResponse> should match
// service_traits::MD5Sum< ::rqt_mypkg::HoverService >
template<>
struct MD5Sum< ::rqt_mypkg::HoverServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rqt_mypkg::HoverService >::value();
  }
  static const char* value(const ::rqt_mypkg::HoverServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rqt_mypkg::HoverServiceResponse> should match
// service_traits::DataType< ::rqt_mypkg::HoverService >
template<>
struct DataType< ::rqt_mypkg::HoverServiceResponse>
{
  static const char* value()
  {
    return DataType< ::rqt_mypkg::HoverService >::value();
  }
  static const char* value(const ::rqt_mypkg::HoverServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RQT_MYPKG_MESSAGE_HOVERSERVICE_H
