// Generated by gencpp from file rqt_mypkg/KillService.msg
// DO NOT EDIT!


#ifndef RQT_MYPKG_MESSAGE_KILLSERVICE_H
#define RQT_MYPKG_MESSAGE_KILLSERVICE_H

#include <ros/service_traits.h>


#include <rqt_mypkg/KillServiceRequest.h>
#include <rqt_mypkg/KillServiceResponse.h>


namespace rqt_mypkg
{

struct KillService
{

typedef KillServiceRequest Request;
typedef KillServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct KillService
} // namespace rqt_mypkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rqt_mypkg::KillService > {
  static const char* value()
  {
    return "2f50e671bde85037531fb7afb9fea841";
  }

  static const char* value(const ::rqt_mypkg::KillService&) { return value(); }
};

template<>
struct DataType< ::rqt_mypkg::KillService > {
  static const char* value()
  {
    return "rqt_mypkg/KillService";
  }

  static const char* value(const ::rqt_mypkg::KillService&) { return value(); }
};


// service_traits::MD5Sum< ::rqt_mypkg::KillServiceRequest> should match
// service_traits::MD5Sum< ::rqt_mypkg::KillService >
template<>
struct MD5Sum< ::rqt_mypkg::KillServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rqt_mypkg::KillService >::value();
  }
  static const char* value(const ::rqt_mypkg::KillServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rqt_mypkg::KillServiceRequest> should match
// service_traits::DataType< ::rqt_mypkg::KillService >
template<>
struct DataType< ::rqt_mypkg::KillServiceRequest>
{
  static const char* value()
  {
    return DataType< ::rqt_mypkg::KillService >::value();
  }
  static const char* value(const ::rqt_mypkg::KillServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rqt_mypkg::KillServiceResponse> should match
// service_traits::MD5Sum< ::rqt_mypkg::KillService >
template<>
struct MD5Sum< ::rqt_mypkg::KillServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rqt_mypkg::KillService >::value();
  }
  static const char* value(const ::rqt_mypkg::KillServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rqt_mypkg::KillServiceResponse> should match
// service_traits::DataType< ::rqt_mypkg::KillService >
template<>
struct DataType< ::rqt_mypkg::KillServiceResponse>
{
  static const char* value()
  {
    return DataType< ::rqt_mypkg::KillService >::value();
  }
  static const char* value(const ::rqt_mypkg::KillServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RQT_MYPKG_MESSAGE_KILLSERVICE_H
