// Generated by gencpp from file rqt_mypkg/KillServiceRequest.msg
// DO NOT EDIT!


#ifndef RQT_MYPKG_MESSAGE_KILLSERVICEREQUEST_H
#define RQT_MYPKG_MESSAGE_KILLSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rqt_mypkg
{
template <class ContainerAllocator>
struct KillServiceRequest_
{
  typedef KillServiceRequest_<ContainerAllocator> Type;

  KillServiceRequest_()
    : Kill_isChecked(false)  {
    }
  KillServiceRequest_(const ContainerAllocator& _alloc)
    : Kill_isChecked(false)  {
  (void)_alloc;
    }



   typedef uint8_t _Kill_isChecked_type;
  _Kill_isChecked_type Kill_isChecked;





  typedef boost::shared_ptr< ::rqt_mypkg::KillServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rqt_mypkg::KillServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct KillServiceRequest_

typedef ::rqt_mypkg::KillServiceRequest_<std::allocator<void> > KillServiceRequest;

typedef boost::shared_ptr< ::rqt_mypkg::KillServiceRequest > KillServiceRequestPtr;
typedef boost::shared_ptr< ::rqt_mypkg::KillServiceRequest const> KillServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rqt_mypkg::KillServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rqt_mypkg::KillServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rqt_mypkg::KillServiceRequest_<ContainerAllocator1> & lhs, const ::rqt_mypkg::KillServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.Kill_isChecked == rhs.Kill_isChecked;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rqt_mypkg::KillServiceRequest_<ContainerAllocator1> & lhs, const ::rqt_mypkg::KillServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rqt_mypkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rqt_mypkg::KillServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rqt_mypkg::KillServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rqt_mypkg::KillServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rqt_mypkg::KillServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rqt_mypkg::KillServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rqt_mypkg::KillServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rqt_mypkg::KillServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f50e671bde85037531fb7afb9fea841";
  }

  static const char* value(const ::rqt_mypkg::KillServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f50e671bde85037ULL;
  static const uint64_t static_value2 = 0x531fb7afb9fea841ULL;
};

template<class ContainerAllocator>
struct DataType< ::rqt_mypkg::KillServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rqt_mypkg/KillServiceRequest";
  }

  static const char* value(const ::rqt_mypkg::KillServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rqt_mypkg::KillServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool Kill_isChecked\n"
;
  }

  static const char* value(const ::rqt_mypkg::KillServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rqt_mypkg::KillServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Kill_isChecked);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct KillServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rqt_mypkg::KillServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rqt_mypkg::KillServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "Kill_isChecked: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Kill_isChecked);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RQT_MYPKG_MESSAGE_KILLSERVICEREQUEST_H
