// Generated by gencpp from file rqt_mypkg/ManipulatorService.msg
// DO NOT EDIT!


#ifndef RQT_MYPKG_MESSAGE_MANIPULATORSERVICE_H
#define RQT_MYPKG_MESSAGE_MANIPULATORSERVICE_H

#include <ros/service_traits.h>


#include <rqt_mypkg/ManipulatorServiceRequest.h>
#include <rqt_mypkg/ManipulatorServiceResponse.h>


namespace rqt_mypkg
{

struct ManipulatorService
{

typedef ManipulatorServiceRequest Request;
typedef ManipulatorServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ManipulatorService
} // namespace rqt_mypkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rqt_mypkg::ManipulatorService > {
  static const char* value()
  {
    return "e97a16db574d49cc1895dbcce93fb70e";
  }

  static const char* value(const ::rqt_mypkg::ManipulatorService&) { return value(); }
};

template<>
struct DataType< ::rqt_mypkg::ManipulatorService > {
  static const char* value()
  {
    return "rqt_mypkg/ManipulatorService";
  }

  static const char* value(const ::rqt_mypkg::ManipulatorService&) { return value(); }
};


// service_traits::MD5Sum< ::rqt_mypkg::ManipulatorServiceRequest> should match
// service_traits::MD5Sum< ::rqt_mypkg::ManipulatorService >
template<>
struct MD5Sum< ::rqt_mypkg::ManipulatorServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rqt_mypkg::ManipulatorService >::value();
  }
  static const char* value(const ::rqt_mypkg::ManipulatorServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rqt_mypkg::ManipulatorServiceRequest> should match
// service_traits::DataType< ::rqt_mypkg::ManipulatorService >
template<>
struct DataType< ::rqt_mypkg::ManipulatorServiceRequest>
{
  static const char* value()
  {
    return DataType< ::rqt_mypkg::ManipulatorService >::value();
  }
  static const char* value(const ::rqt_mypkg::ManipulatorServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rqt_mypkg::ManipulatorServiceResponse> should match
// service_traits::MD5Sum< ::rqt_mypkg::ManipulatorService >
template<>
struct MD5Sum< ::rqt_mypkg::ManipulatorServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rqt_mypkg::ManipulatorService >::value();
  }
  static const char* value(const ::rqt_mypkg::ManipulatorServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rqt_mypkg::ManipulatorServiceResponse> should match
// service_traits::DataType< ::rqt_mypkg::ManipulatorService >
template<>
struct DataType< ::rqt_mypkg::ManipulatorServiceResponse>
{
  static const char* value()
  {
    return DataType< ::rqt_mypkg::ManipulatorService >::value();
  }
  static const char* value(const ::rqt_mypkg::ManipulatorServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RQT_MYPKG_MESSAGE_MANIPULATORSERVICE_H
