// Generated by gencpp from file rqt_mypkg/TiltServiceRequest.msg
// DO NOT EDIT!


#ifndef RQT_MYPKG_MESSAGE_TILTSERVICEREQUEST_H
#define RQT_MYPKG_MESSAGE_TILTSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rqt_mypkg
{
template <class ContainerAllocator>
struct TiltServiceRequest_
{
  typedef TiltServiceRequest_<ContainerAllocator> Type;

  TiltServiceRequest_()
    : Tilt_isChecked(false)  {
    }
  TiltServiceRequest_(const ContainerAllocator& _alloc)
    : Tilt_isChecked(false)  {
  (void)_alloc;
    }



   typedef uint8_t _Tilt_isChecked_type;
  _Tilt_isChecked_type Tilt_isChecked;





  typedef boost::shared_ptr< ::rqt_mypkg::TiltServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rqt_mypkg::TiltServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TiltServiceRequest_

typedef ::rqt_mypkg::TiltServiceRequest_<std::allocator<void> > TiltServiceRequest;

typedef boost::shared_ptr< ::rqt_mypkg::TiltServiceRequest > TiltServiceRequestPtr;
typedef boost::shared_ptr< ::rqt_mypkg::TiltServiceRequest const> TiltServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rqt_mypkg::TiltServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rqt_mypkg::TiltServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rqt_mypkg::TiltServiceRequest_<ContainerAllocator1> & lhs, const ::rqt_mypkg::TiltServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.Tilt_isChecked == rhs.Tilt_isChecked;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rqt_mypkg::TiltServiceRequest_<ContainerAllocator1> & lhs, const ::rqt_mypkg::TiltServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rqt_mypkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::rqt_mypkg::TiltServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rqt_mypkg::TiltServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rqt_mypkg::TiltServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rqt_mypkg::TiltServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rqt_mypkg::TiltServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rqt_mypkg::TiltServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rqt_mypkg::TiltServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "255a80a4a8236b9a7fbfacc2e90e9a25";
  }

  static const char* value(const ::rqt_mypkg::TiltServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x255a80a4a8236b9aULL;
  static const uint64_t static_value2 = 0x7fbfacc2e90e9a25ULL;
};

template<class ContainerAllocator>
struct DataType< ::rqt_mypkg::TiltServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rqt_mypkg/TiltServiceRequest";
  }

  static const char* value(const ::rqt_mypkg::TiltServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rqt_mypkg::TiltServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool Tilt_isChecked\n"
;
  }

  static const char* value(const ::rqt_mypkg::TiltServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rqt_mypkg::TiltServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Tilt_isChecked);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TiltServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rqt_mypkg::TiltServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rqt_mypkg::TiltServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "Tilt_isChecked: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Tilt_isChecked);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RQT_MYPKG_MESSAGE_TILTSERVICEREQUEST_H
