// Generated by gencpp from file open_manipulator_msgs/DockBatteryService.msg
// DO NOT EDIT!


#ifndef OPEN_MANIPULATOR_MSGS_MESSAGE_DOCKBATTERYSERVICE_H
#define OPEN_MANIPULATOR_MSGS_MESSAGE_DOCKBATTERYSERVICE_H

#include <ros/service_traits.h>


#include <open_manipulator_msgs/DockBatteryServiceRequest.h>
#include <open_manipulator_msgs/DockBatteryServiceResponse.h>


namespace open_manipulator_msgs
{

struct DockBatteryService
{

typedef DockBatteryServiceRequest Request;
typedef DockBatteryServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DockBatteryService
} // namespace open_manipulator_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::open_manipulator_msgs::DockBatteryService > {
  static const char* value()
  {
    return "176118c4f805289b178b248bb86fc0ac";
  }

  static const char* value(const ::open_manipulator_msgs::DockBatteryService&) { return value(); }
};

template<>
struct DataType< ::open_manipulator_msgs::DockBatteryService > {
  static const char* value()
  {
    return "open_manipulator_msgs/DockBatteryService";
  }

  static const char* value(const ::open_manipulator_msgs::DockBatteryService&) { return value(); }
};


// service_traits::MD5Sum< ::open_manipulator_msgs::DockBatteryServiceRequest> should match
// service_traits::MD5Sum< ::open_manipulator_msgs::DockBatteryService >
template<>
struct MD5Sum< ::open_manipulator_msgs::DockBatteryServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::open_manipulator_msgs::DockBatteryService >::value();
  }
  static const char* value(const ::open_manipulator_msgs::DockBatteryServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::open_manipulator_msgs::DockBatteryServiceRequest> should match
// service_traits::DataType< ::open_manipulator_msgs::DockBatteryService >
template<>
struct DataType< ::open_manipulator_msgs::DockBatteryServiceRequest>
{
  static const char* value()
  {
    return DataType< ::open_manipulator_msgs::DockBatteryService >::value();
  }
  static const char* value(const ::open_manipulator_msgs::DockBatteryServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::open_manipulator_msgs::DockBatteryServiceResponse> should match
// service_traits::MD5Sum< ::open_manipulator_msgs::DockBatteryService >
template<>
struct MD5Sum< ::open_manipulator_msgs::DockBatteryServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::open_manipulator_msgs::DockBatteryService >::value();
  }
  static const char* value(const ::open_manipulator_msgs::DockBatteryServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::open_manipulator_msgs::DockBatteryServiceResponse> should match
// service_traits::DataType< ::open_manipulator_msgs::DockBatteryService >
template<>
struct DataType< ::open_manipulator_msgs::DockBatteryServiceResponse>
{
  static const char* value()
  {
    return DataType< ::open_manipulator_msgs::DockBatteryService >::value();
  }
  static const char* value(const ::open_manipulator_msgs::DockBatteryServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPEN_MANIPULATOR_MSGS_MESSAGE_DOCKBATTERYSERVICE_H
