// Generated by gencpp from file open_manipulator_msgs/KillManipulatorService.msg
// DO NOT EDIT!


#ifndef OPEN_MANIPULATOR_MSGS_MESSAGE_KILLMANIPULATORSERVICE_H
#define OPEN_MANIPULATOR_MSGS_MESSAGE_KILLMANIPULATORSERVICE_H

#include <ros/service_traits.h>


#include <open_manipulator_msgs/KillManipulatorServiceRequest.h>
#include <open_manipulator_msgs/KillManipulatorServiceResponse.h>


namespace open_manipulator_msgs
{

struct KillManipulatorService
{

typedef KillManipulatorServiceRequest Request;
typedef KillManipulatorServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct KillManipulatorService
} // namespace open_manipulator_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::open_manipulator_msgs::KillManipulatorService > {
  static const char* value()
  {
    return "9a01135ee4671c8756692e8e401a879e";
  }

  static const char* value(const ::open_manipulator_msgs::KillManipulatorService&) { return value(); }
};

template<>
struct DataType< ::open_manipulator_msgs::KillManipulatorService > {
  static const char* value()
  {
    return "open_manipulator_msgs/KillManipulatorService";
  }

  static const char* value(const ::open_manipulator_msgs::KillManipulatorService&) { return value(); }
};


// service_traits::MD5Sum< ::open_manipulator_msgs::KillManipulatorServiceRequest> should match
// service_traits::MD5Sum< ::open_manipulator_msgs::KillManipulatorService >
template<>
struct MD5Sum< ::open_manipulator_msgs::KillManipulatorServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::open_manipulator_msgs::KillManipulatorService >::value();
  }
  static const char* value(const ::open_manipulator_msgs::KillManipulatorServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::open_manipulator_msgs::KillManipulatorServiceRequest> should match
// service_traits::DataType< ::open_manipulator_msgs::KillManipulatorService >
template<>
struct DataType< ::open_manipulator_msgs::KillManipulatorServiceRequest>
{
  static const char* value()
  {
    return DataType< ::open_manipulator_msgs::KillManipulatorService >::value();
  }
  static const char* value(const ::open_manipulator_msgs::KillManipulatorServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::open_manipulator_msgs::KillManipulatorServiceResponse> should match
// service_traits::MD5Sum< ::open_manipulator_msgs::KillManipulatorService >
template<>
struct MD5Sum< ::open_manipulator_msgs::KillManipulatorServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::open_manipulator_msgs::KillManipulatorService >::value();
  }
  static const char* value(const ::open_manipulator_msgs::KillManipulatorServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::open_manipulator_msgs::KillManipulatorServiceResponse> should match
// service_traits::DataType< ::open_manipulator_msgs::KillManipulatorService >
template<>
struct DataType< ::open_manipulator_msgs::KillManipulatorServiceResponse>
{
  static const char* value()
  {
    return DataType< ::open_manipulator_msgs::KillManipulatorService >::value();
  }
  static const char* value(const ::open_manipulator_msgs::KillManipulatorServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OPEN_MANIPULATOR_MSGS_MESSAGE_KILLMANIPULATORSERVICE_H
