// Generated by gencpp from file open_manipulator_msgs/ManipulatorServiceRequest.msg
// DO NOT EDIT!


#ifndef OPEN_MANIPULATOR_MSGS_MESSAGE_MANIPULATORSERVICEREQUEST_H
#define OPEN_MANIPULATOR_MSGS_MESSAGE_MANIPULATORSERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace open_manipulator_msgs
{
template <class ContainerAllocator>
struct ManipulatorServiceRequest_
{
  typedef ManipulatorServiceRequest_<ContainerAllocator> Type;

  ManipulatorServiceRequest_()
    : Manipul(false)  {
    }
  ManipulatorServiceRequest_(const ContainerAllocator& _alloc)
    : Manipul(false)  {
  (void)_alloc;
    }



   typedef uint8_t _Manipul_type;
  _Manipul_type Manipul;





  typedef boost::shared_ptr< ::open_manipulator_msgs::ManipulatorServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::open_manipulator_msgs::ManipulatorServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ManipulatorServiceRequest_

typedef ::open_manipulator_msgs::ManipulatorServiceRequest_<std::allocator<void> > ManipulatorServiceRequest;

typedef boost::shared_ptr< ::open_manipulator_msgs::ManipulatorServiceRequest > ManipulatorServiceRequestPtr;
typedef boost::shared_ptr< ::open_manipulator_msgs::ManipulatorServiceRequest const> ManipulatorServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::open_manipulator_msgs::ManipulatorServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::open_manipulator_msgs::ManipulatorServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::open_manipulator_msgs::ManipulatorServiceRequest_<ContainerAllocator1> & lhs, const ::open_manipulator_msgs::ManipulatorServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.Manipul == rhs.Manipul;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::open_manipulator_msgs::ManipulatorServiceRequest_<ContainerAllocator1> & lhs, const ::open_manipulator_msgs::ManipulatorServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace open_manipulator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::open_manipulator_msgs::ManipulatorServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::open_manipulator_msgs::ManipulatorServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::open_manipulator_msgs::ManipulatorServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::open_manipulator_msgs::ManipulatorServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::open_manipulator_msgs::ManipulatorServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::open_manipulator_msgs::ManipulatorServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::open_manipulator_msgs::ManipulatorServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e97a16db574d49cc1895dbcce93fb70e";
  }

  static const char* value(const ::open_manipulator_msgs::ManipulatorServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe97a16db574d49ccULL;
  static const uint64_t static_value2 = 0x1895dbcce93fb70eULL;
};

template<class ContainerAllocator>
struct DataType< ::open_manipulator_msgs::ManipulatorServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "open_manipulator_msgs/ManipulatorServiceRequest";
  }

  static const char* value(const ::open_manipulator_msgs::ManipulatorServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::open_manipulator_msgs::ManipulatorServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool Manipul\n"
;
  }

  static const char* value(const ::open_manipulator_msgs::ManipulatorServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::open_manipulator_msgs::ManipulatorServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Manipul);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ManipulatorServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::open_manipulator_msgs::ManipulatorServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::open_manipulator_msgs::ManipulatorServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "Manipul: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Manipul);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPEN_MANIPULATOR_MSGS_MESSAGE_MANIPULATORSERVICEREQUEST_H
